// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TaxiBotTest.Data;

#nullable disable

namespace TaxiBotTest.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260329160218_Init")]
    partial class Init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.0");

            modelBuilder.Entity("TaxiBot.Models.Entities.Message", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsFromOperator")
                        .HasColumnType("INTEGER");

                    b.Property<int>("RequestId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("SenderOperatorId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("SenderTelegramUserId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("SentAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("RequestId");

                    b.HasIndex("SenderOperatorId");

                    b.HasIndex("SenderTelegramUserId");

                    b.ToTable("Messages");
                });

            modelBuilder.Entity("TaxiBot.Models.Entities.OperatorEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsAvailable")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Login")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("RegisteredAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Login")
                        .IsUnique();

                    b.ToTable("Operators");
                });

            modelBuilder.Entity("TaxiBot.Models.Entities.Request", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("AssignedAt")
                        .HasColumnType("TEXT");

                    b.Property<int?>("AssignedOperatorId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("InitialMessage")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("ProblemType")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TelegramUserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("AssignedOperatorId");

                    b.HasIndex("TelegramUserId");

                    b.ToTable("Requests");
                });

            modelBuilder.Entity("TaxiBot.Models.Entities.TelegramUser", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<long>("ChatId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsRegistered")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Language")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("RegisteredAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Username")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ChatId")
                        .IsUnique();

                    b.ToTable("TelegramUsers");
                });

            modelBuilder.Entity("TaxiBot.Models.Entities.Message", b =>
                {
                    b.HasOne("TaxiBot.Models.Entities.Request", "Request")
                        .WithMany("Messages")
                        .HasForeignKey("RequestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TaxiBot.Models.Entities.OperatorEntity", "SenderOperator")
                        .WithMany()
                        .HasForeignKey("SenderOperatorId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("TaxiBot.Models.Entities.TelegramUser", "SenderTelegramUser")
                        .WithMany()
                        .HasForeignKey("SenderTelegramUserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Request");

                    b.Navigation("SenderOperator");

                    b.Navigation("SenderTelegramUser");
                });

            modelBuilder.Entity("TaxiBot.Models.Entities.Request", b =>
                {
                    b.HasOne("TaxiBot.Models.Entities.OperatorEntity", "AssignedOperator")
                        .WithMany("AssignedRequests")
                        .HasForeignKey("AssignedOperatorId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("TaxiBot.Models.Entities.TelegramUser", "TelegramUser")
                        .WithMany("Requests")
                        .HasForeignKey("TelegramUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("AssignedOperator");

                    b.Navigation("TelegramUser");
                });

            modelBuilder.Entity("TaxiBot.Models.Entities.OperatorEntity", b =>
                {
                    b.Navigation("AssignedRequests");
                });

            modelBuilder.Entity("TaxiBot.Models.Entities.Request", b =>
                {
                    b.Navigation("Messages");
                });

            modelBuilder.Entity("TaxiBot.Models.Entities.TelegramUser", b =>
                {
                    b.Navigation("Requests");
                });
#pragma warning restore 612, 618
        }
    }
}
